Update and rename jtvplus6.yml to JioTV_S5.yml

diff --git a/.github/workflows/JioTV_S5.yml b/.github/workflows/JioTV_S5.yml
--- a/.github/workflows/JioTV_S5.yml
+++ b/.github/workflows/JioTV_S5.yml
@@ -1,21 +1,24 @@
-name: Update JTV PLUS 6 Playlist
+name: Update JioTV Server 5
+
 on:
   schedule:
-    - cron: '0 */1 * * *'
+    - cron: '0 */3 * * *'
   workflow_dispatch:
   push:
     branches:
       - main
     paths:
-      - 'jtvplus6.py'
+      - 'scripts/JioTV_S5.py'
+
 jobs:
   update-playlist:
     runs-on: ubuntu-latest
     permissions:
       contents: write
     concurrency:
-      group: update-jtv2
+      group: update-jiotv-s5
       cancel-in-progress: true
+      
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -25,8 +28,8 @@ jobs:
 
       - name: Configure Git
         run: |
-          git config --global user.name "sportlive18"
-          git config --global user.email "271363488+sportlive18@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
       - name: Fetch and Reset to Remote
         run: |
@@ -38,27 +41,22 @@ jobs:
         with:
           python-version: "3.x"
 
-      - name: Install Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install requests pytz
-
       - name: Run Script
         env:
           TZ: Asia/Kolkata
         run: |
-          python jtvplus6.py
+          python scripts/JioTV_S5.py
 
       - name: Commit and Push Changes
         run: |
-          git add jtvplus6.m3u
+          git add Playlists/JioTV_S5.m3u
 
           if git diff --cached --quiet; then
             echo "No changes to commit."
             exit 0
           fi
 
-          git commit -m "JIOTV Updated ✅ ($(date -u '+%Y-%m-%d %H:%M UTC'))"
+          git commit -m "GmaxHub JioTV S5 Updated ✅ ($(date -u '+%Y-%m-%d %H:%M UTC'))"
 
           max_retries=5
           attempt=1
@@ -79,4 +77,5 @@ jobs:
             fi
           done
 
-          echo "Push
+          echo "Push failed after $max_retries attempts."
+          exit 1
